name: kavach
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  vector_map_tiles: ^8.0.0
  vector_tile_renderer: ^5.2.0
  supabase_flutter: ^2.6.0
  flutter_map_heatmap:
    path: ./fluttermap_heatmap
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  flutter_expandable_fab: ^2.3.0
  keyboard_detection: ^0.7.3
  twilio_flutter: ^0.9.0
  flutter_otp_text_field: ^1.2.0
  flutter_map_location_marker:
      git: 
        url: https://github.com/domhel/flutter_map_location_marker.git
        ref: 1c6d946
  # flutter_compass: '^0.8.0'
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  share_plus: ^10.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/title_image.png
        - assets/images/fab/shield.png
        - assets/images/fab/children.png
        - assets/images/fab/physical.png
        - assets/images/fab/natural.png
        - assets/images/fab/street.png
        - assets/images/fab/theft.png
        - assets/images/fab/harassment.png
        - assets/images/fab/volatile.png
        - assets/images/

        # An image asset can refer to one or more resolution-specific "variants", see
        # https://flutter.dev/to/resolution-aware-images

        # For details regarding adding assets from package dependencies, see
        # https://flutter.dev/to/asset-from-package

        # To add custom fonts to your application, add a fonts section here,
        # in this "flutter" section. Each entry in this list should have a
        # "family" key with the font family name, and a "fonts" key with a
        # list giving the asset and other descriptors for the font. For
        # example:
        # fonts:
        #   - family: Schyler
        #     fonts:
        #       - asset: fonts/Schyler-Regular.ttf
        #       - asset: fonts/Schyler-Italic.ttf
        #         style: italic
        #   - family: Trajan Pro
        #     fonts:
        #       - asset: fonts/TrajanPro.ttf
        #       - asset: fonts/TrajanPro_Bold.ttf
        #         weight: 700
        #
        # For details regarding fonts from package dependencies,
        # see https://flutter.dev/to/font-from-package
